#!/bin/bash
# Shared Zenoh helpers (router + client). Sourced by entrypoints / run scripts.
#
# Env (optional, from .env / compose):
#   ZENOH_ROUTER_HOST   — LAN IP of the host router (stretch3 clients), default 192.168.0.246
#   ZENOH_ROUTER_PORT   — listen/connect port, default 7447
#   ZENOH_HOST_CLIENT_ENDPOINT — host-local clients (4060ti), default 127.0.0.1:7447

zenoh_router_port() {
  echo "${ZENOH_ROUTER_PORT:-7447}"
}

zenoh_router_host() {
  echo "${ZENOH_ROUTER_HOST:-192.168.0.246}"
}

# Endpoint used by containers on the GPU host (network_mode: host → loopback).
zenoh_host_client_endpoint() {
  echo "${ZENOH_HOST_CLIENT_ENDPOINT:-127.0.0.1:$(zenoh_router_port)}"
}

# Endpoint used by remote robots (stretch3).
zenoh_remote_client_endpoint() {
  echo "$(zenoh_router_host):$(zenoh_router_port)"
}

zenoh_source_ros() {
  if [ -f /opt/ros/humble/setup.bash ]; then
    local _nounset_was_on=0
    case "$-" in *u*) _nounset_was_on=1 ;; esac
    set +u
    # shellcheck disable=SC1091
    source /opt/ros/humble/setup.bash
    if [ "${_nounset_was_on}" -eq 1 ]; then
      set -u
    fi
  fi
}

zenoh_apply_router_env() {
  local port
  port="$(zenoh_router_port)"
  export RMW_IMPLEMENTATION="${RMW_IMPLEMENTATION:-rmw_zenoh_cpp}"
  export ROS_DOMAIN_ID="${ROS_DOMAIN_ID:-0}"
  # Listen on all interfaces so stretch3 (and other hosts) can reach the router.
  export ZENOH_CONFIG_OVERRIDE="listen/endpoints=[\"tcp/0.0.0.0:${port}\"]"
}

# $1 = connect endpoint host:port (e.g. 127.0.0.1:7447 or 192.168.0.246:7447)
zenoh_apply_client_env() {
  local endpoint="${1:?client endpoint required}"
  export RMW_IMPLEMENTATION="${RMW_IMPLEMENTATION:-rmw_zenoh_cpp}"
  export ROS_DOMAIN_ID="${ROS_DOMAIN_ID:-0}"
  export ZENOH_CONFIG_OVERRIDE="mode=\"client\";connect/endpoints=[\"tcp/${endpoint}\"]"
}

# Persist client exports for interactive `docker compose exec` shells.
zenoh_persist_client_profile() {
  local label="${1:-zenoh-client}"
  if [ ! -d /etc/profile.d ]; then
    return 0
  fi
  cat >/etc/profile.d/vlmotion-zenoh.sh <<EOF
# Generated by ${label} — Zenoh client session
export RMW_IMPLEMENTATION="${RMW_IMPLEMENTATION}"
export ROS_DOMAIN_ID="${ROS_DOMAIN_ID}"
export ZENOH_CONFIG_OVERRIDE='${ZENOH_CONFIG_OVERRIDE}'
EOF
  if [ -f /etc/bash.bashrc ] && ! grep -q 'vlmotion-zenoh.sh' /etc/bash.bashrc 2>/dev/null; then
    echo '[ -f /etc/profile.d/vlmotion-zenoh.sh ] && . /etc/profile.d/vlmotion-zenoh.sh' >>/etc/bash.bashrc
  fi
}

zenoh_port_open() {
  local host="${1:-127.0.0.1}"
  local port="${2:-$(zenoh_router_port)}"
  (echo >/dev/tcp/"${host}"/"${port}") >/dev/null 2>&1
}

# Wait until router accepts TCP on host:port (default loopback).
zenoh_wait_for_router() {
  local host="${1:-127.0.0.1}"
  local port="${2:-$(zenoh_router_port)}"
  local tries="${3:-40}"
  local i
  for i in $(seq 1 "${tries}"); do
    if zenoh_port_open "${host}" "${port}"; then
      return 0
    fi
    sleep 0.25
  done
  return 1
}
