<?xml version="1.0"?>
<package format="3">
  <name>vlmotion_robot_bridge</name>
  <version>0.1.0</version>
  <description>Forward VLMotion base velocity to the Stretch driver.</description>
  <maintainer email="hrc@example.com">hrc</maintainer>
  <license>Apache-2.0</license>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
