#!/usr/bin/env python3
"""
Gripper Alignment Tuning Tool
Interactive tool to adjust gripper alignment parameters
"""

import sys
import os

# Add VLServo to path
sys.path.insert(0, '/workspace/ros2_ws/src/vlservo')

from VLServo.base_motion_ros2 import PostGraspConfig

def print_header():
    print("=" * 60)
    print(" 🤖 Gripper Alignment Configuration Tuning Tool")
    print("=" * 60)
    print()

def print_current_config(cfg: PostGraspConfig):
    print("\n📋 Current Configuration:")
    print("-" * 60)
    print(f"  Base Turn (chassis left):     {cfg.base_turn_deg:>7.1f}°")
    print(f"  Head Pan (compensate right):  {cfg.head_pan_deg:>7.1f}°")
    print(f"  Wrist Yaw (forward):          {cfg.wrist_yaw_deg:>7.1f}°")
    print(f"  Wrist Roll (finger orient):   {cfg.wrist_roll_deg:>7.1f}°")
    if cfg.wrist_pitch_deg is not None:
        print(f"  Wrist Pitch:                  {cfg.wrist_pitch_deg:>7.1f}°")
    else:
        print(f"  Wrist Pitch:                  {'None':>7}")
    print()
    print(f"  Lift Offset:                  {cfg.lift_offset_m:>7.3f} m")
    print(f"  Min Lift:                     {cfg.min_lift_m:>7.3f} m")
    print(f"  Max Lift:                     {cfg.max_lift_m:>7.3f} m")
    print(f"  Arm Offset (retracted dist):  {cfg.arm_offset_m:>7.3f} m")
    print(f"  Max Arm Extension:            {cfg.max_arm_extension_m:>7.3f} m")
    print("-" * 60)

def generate_command(cfg: PostGraspConfig, target_x=640, target_y=360):
    """Generate the command line with current configuration"""
    cmd = f"""python3 -m VLServo.base_motion_ros2 \\
  -x {target_x} \\
  -y {target_y} \\
  --camera d435i \\
  --stop-dist-m 0.5 \\
  --tilt-down-negative \\
  --post-grasp-base-turn {cfg.base_turn_deg} \\
  --post-grasp-head-pan {cfg.head_pan_deg} \\
  --post-grasp-lift-offset {cfg.lift_offset_m} \\
  --post-grasp-arm-offset {cfg.arm_offset_m} \\
  --post-grasp-wrist-yaw-deg {cfg.wrist_yaw_deg} \\
  --post-grasp-wrist-roll-deg {cfg.wrist_roll_deg}"""
    
    if cfg.wrist_pitch_deg is not None:
        cmd += f" \\\n  --post-grasp-wrist-pitch-deg {cfg.wrist_pitch_deg}"
    
    return cmd

def save_to_script(cfg: PostGraspConfig, target_x=640, target_y=360, filename="custom_alignment.sh"):
    """Save configuration to a bash script"""
    cmd = generate_command(cfg, target_x, target_y)
    
    script_content = f"""#!/bin/bash
# Custom Gripper Alignment Configuration
# Generated by gripper_alignment_tuner.py

source /workspace/ros2_ws/install/setup.bash

echo "🤖 Running gripper alignment with custom configuration..."
echo ""

{cmd}

echo ""
echo "✅ Alignment test completed"
"""
    
    filepath = f"/workspace/{filename}"
    with open(filepath, 'w') as f:
        f.write(script_content)
    
    os.chmod(filepath, 0o755)
    print(f"\n✅ Configuration saved to: {filepath}")
    print(f"   Run with: {filepath}")

def main():
    print_header()
    
    # Start with default configuration
    cfg = PostGraspConfig()
    
    print("📝 This tool helps you tune the gripper alignment parameters.")
    print("   Adjust values based on your observations.")
    print()
    
    print_current_config(cfg)
    
    print("\n🎯 Common Scenarios:")
    print()
    print("1. 🔄 Standard configuration (TF-corrected for Stretch)")
    print("   - Base turn: 60°, Head pan: 60° (gripper at y=-0.21m)")
    print("   - Wrist roll: 0° (horizontal fingers)")
    print()
    print("2. 📦 Top-down grasp (from above)")
    print("   - Base turn: 60°, Head pan: 60°")
    print("   - Wrist roll: -45° (fingers tilted down)")
    print()
    print("3. 🤏 Side grasp (from the side)")
    print("   - Base turn: 60°, Head pan: 60°")
    print("   - Wrist roll: -90° (fingers vertical)")
    print()
    print("4. 🎪 Fine-tune existing setup")
    print("   - Custom values")
    print()
    
    choice = input("Select scenario (1-4) or press Enter to use defaults: ").strip()
    
    if choice == "2":
        # Top-down grasp
        cfg.base_turn_deg = 60.0
        cfg.head_pan_deg = 60.0
        cfg.wrist_roll_deg = -45.0
        cfg.wrist_yaw_deg = 90.0
        print("\n✅ Applied: Top-down grasp configuration")
    
    elif choice == "3":
        # Side grasp
        cfg.base_turn_deg = 60.0
        cfg.head_pan_deg = 60.0
        cfg.wrist_roll_deg = -90.0
        cfg.wrist_yaw_deg = 90.0
        print("\n✅ Applied: Side grasp configuration")
    
    elif choice == "4":
        # Custom tuning
        print("\n🔧 Enter custom values (press Enter to keep current):")
        
        val = input(f"  Base turn [{cfg.base_turn_deg}°]: ").strip()
        if val:
            cfg.base_turn_deg = float(val)
        
        val = input(f"  Head pan [{cfg.head_pan_deg}°]: ").strip()
        if val:
            cfg.head_pan_deg = float(val)
        
        val = input(f"  Wrist yaw [{cfg.wrist_yaw_deg}°]: ").strip()
        if val:
            cfg.wrist_yaw_deg = float(val)
        
        val = input(f"  Wrist roll [{cfg.wrist_roll_deg}°]: ").strip()
        if val:
            cfg.wrist_roll_deg = float(val)
        
        val = input(f"  Wrist pitch [None]: ").strip()
        if val:
            cfg.wrist_pitch_deg = float(val)
        
        val = input(f"  Lift offset [{cfg.lift_offset_m} m]: ").strip()
        if val:
            cfg.lift_offset_m = float(val)
        
        val = input(f"  Arm offset [{cfg.arm_offset_m} m]: ").strip()
        if val:
            cfg.arm_offset_m = float(val)
        
        print("\n✅ Custom configuration applied")
    
    else:
        # Use defaults (scenario 1)
        cfg.base_turn_deg = 60.0
        cfg.head_pan_deg = 60.0
        cfg.wrist_roll_deg = 0.0
        print("\n✅ Using standard configuration (TF-corrected)")
    
    print_current_config(cfg)
    
    # Get target pixel coordinates
    print("\n🎯 Target Pixel Coordinates:")
    target_x = input("  Target X [640]: ").strip()
    target_x = int(target_x) if target_x else 640
    
    target_y = input("  Target Y [360]: ").strip()
    target_y = int(target_y) if target_y else 360
    
    print(f"\n✅ Target: ({target_x}, {target_y})")
    
    # Generate command
    print("\n" + "=" * 60)
    print(" 📜 Generated Command:")
    print("=" * 60)
    print()
    print(generate_command(cfg, target_x, target_y))
    print()
    
    # Offer to save
    save = input("\n💾 Save to script file? (y/n) [y]: ").strip().lower()
    
    if save != 'n':
        filename = input("  Filename [custom_alignment.sh]: ").strip()
        if not filename:
            filename = "custom_alignment.sh"
        
        if not filename.endswith('.sh'):
            filename += '.sh'
        
        save_to_script(cfg, target_x, target_y, filename)
    
    print("\n" + "=" * 60)
    print(" ✅ Configuration complete!")
    print("=" * 60)
    print()
    print("📌 Next Steps:")
    print("  1. Source ROS2: source /workspace/ros2_ws/install/setup.bash")
    print("  2. Launch vlservo: ros2 launch vlservo vlservoing_ros2.launch.py")
    print("  3. In GUI, click target and start navigation")
    print("     (or run the generated script directly)")
    print()

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⚠️ Cancelled by user")
        sys.exit(0)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
